feat: flow 활성화/비활성화
shinhan-flow/shinhan-flow-service pull request #112
Opened 2024-08-27 13:26 UTC by minjumost

## #️⃣연관된 이슈

#109 

## 📝작업 내용

플로우 활성화 여부를 변경하고 결과를 반환합니다.
true면 활성화, false면 비활성화 입니다.

2024-08-27 13:39 UTC, gwonhong requested changes
함수명 관련 코멘트 남겼습니다. 확인 부탁드립니다!

2024-08-27 13:39 UTC, gwonhong commented on be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/FlowEntity.java
> +	public Boolean active() {
사소한거지만 함수명 toggleStatus 정도로 하는 게 어떨까 싶습니다.

2024-08-27 13:39 UTC, gwonhong commented on be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/flow/FlowService.java
> +	public Boolean activeFlow(Long memberId, Long flowId) {
이것도 함수명에 toggle이 명시되어야 좋을 것 같아요. toggleFlowStatus 정도?

2024-08-28 00:17 UTC, InGyu-Moon approved these changes
권님이 말씀하신 함수 이름 수정하면 될것 같습니다!

2024-08-28 01:20 UTC, minjumost commented on be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/FlowEntity.java
> +	public Boolean active() {
toggle이란말은 어색해보이는데 switch는 어떠십니까

2024-08-28 04:26 UTC, gwonhong commented on be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/FlowEntity.java
> +	public Boolean active() {
그렇다면 차라리 negate가 나을꺼같습니다

2024-08-28 04:53 UTC, gwonhong approved these changes
수고하셨습니다!

2024-08-28 06:56 UTC, merged