20 feat jwt 토큰 생성
shinhan-flow/shinhan-flow-service pull request #38
Opened 2024-08-22 08:05 UTC by InGyu-Moon

## #️⃣연관된 이슈

> #20 

## 📝작업 내용

> 스프링 시큐리티 설정
> Access, Refresh Token 생성
> Access Token 재발급
> Token 검증
> Token 디코딩

## 💬리뷰 요구사항(선택)
> Refresh Token을 이용한 Access Token 재발급 로직이 올바르게 동작하는지 확인해주세요
> 코드가 읽기 쉽고, 이해하기 쉬운지 검토 부탁 드립니다.
> 스프링 시큐리티를 이용한 로그인 기능은 별도의 이슈로 생성해 진행하겠습니다.

2024-08-22 13:16 UTC, minjumost requested changes
RefreshTokenService와 Controller (AccessToken 재발급 로직) 의 코드를 빼서 JWT Filter 단에서 동작하게 하는게 좋을 것 같아요

2024-08-22 13:16 UTC, minjumost commented on be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/JwtConstants.java
> +    public static final long ACCESS_TOKEN_EXPIRE_TIME = 300 * 1000L; // 30초
application.yml 에서 값 관리

2024-08-22 13:16 UTC, minjumost commented on be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/CorsMvcConfig.java
> +			.allowedOrigins("http://localhost:3000")
하드코딩

2024-08-22 14:45 UTC, InGyu-Moon commented on be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/JwtConstants.java
> +    public static final long ACCESS_TOKEN_EXPIRE_TIME = 300 * 1000L; // 30초
수정완료 😄

2024-08-23 01:26 UTC, minjumost approved these changes

2024-08-23 01:27 UTC, merged